import yfinance as yf
import pandas as pd
import numpy as np
from xgboost import XGBClassifier
from langchain_core.tools import tool

@tool
def stock_price_predictor(ticker: str) -> str:
    """
    Predicts the short-term price direction (Up or Down) for a stock ticker for the next trading day.
    Uses an XGBoost Machine Learning model trained on recent historical data to generate probabilities.
    Call this tool when the user asks for a prediction, forecast, or confidence interval about future stock price movement.
    """
    try:
        # try to get 2 years, though some stocks might be newer
        stock = yf.Ticker(ticker)
        df = stock.history(period="2y")
        
        if len(df) < 50:
            return f"Not enough historical data to generate a reliable prediction for '{ticker}'."
        
        # quick feature engineering
        # TODO: maybe add MACD or RSI here later if accuracy is low
        df['Return'] = df['Close'].pct_change()
        df['SMA_10'] = df['Close'].rolling(window=10).mean()
        df['SMA_50'] = df['Close'].rolling(window=50).mean()
        df['Volatility'] = df['Return'].rolling(window=10).std()
        
        # 1 if tomorrow is greener than today, 0 otherwise
        df['Target'] = (df['Close'].shift(-1) > df['Close']).astype(int)
        
        df = df.dropna()
        
        if len(df) < 50:
            return f"Not enough valid features to generate a prediction for '{ticker}'."

        features = ['Return', 'SMA_10', 'SMA_50', 'Volatility']
        X = df[features]
        y = df['Target']
        
        # train a really basic xgboost model on the fly
        # (hyperparameter tuning takes too long for the live chat block)
        model = XGBClassifier(
            n_estimators=50, 
            max_depth=3, 
            learning_rate=0.1, 
            eval_metric='logloss',
            random_state=42
        )
        model.fit(X, y)
        
        # pull the very last row we have to predict tomorrow
        latest_features = X.iloc[-1:]
        probabilities = model.predict_proba(latest_features)[0]
        
        prob_down = probabilities[0] * 100
        prob_up = probabilities[1] * 100
        
        prediction_direction = "UP" if prob_up > prob_down else "DOWN"
        confidence = max(prob_up, prob_down)
        
        report = (
            f"ML Forecasting Model Results for {ticker.upper()}:\n"
            f"- Prediction for next trading day: {prediction_direction}\n"
            f"- Confidence Interval (Probabilities):\n"
            f"  * UP: {prob_up:.1f}%\n"
            f"  * DOWN: {prob_down:.1f}%\n"
            f"(Note: These probabilities are generated by an XGBoost classification model evaluating recent momentum metrics. It is not financial advice.)"
        )
        return report
        
    except Exception as e:
        return f"Error running ML prediction model for {ticker}: {str(e)}"
